Substitui "Editais" para "Projetos"
softeam-org/icose-web pull request #18
Opened 2023-08-18 16:25 UTC by DanielSenaDev

Substitui o nome "Editais" para "Projetos" dentro das pages.js e no Footer.jsx
Agora
- Arquivo da página se chama Projetos
- Função dentro da página se chama Projects

2023-08-19 01:24 UTC, biribas requested changes
Consertar problemas citados

2023-08-19 01:24 UTC, biribas commented on src/Pages/Projetos.jsx
Crie um componente Project para cada projeto. Crie ele numa pasta Projetos dentro da pasta components (para manter o padrão de organização criado até então).

Além disso, o background color da página não está ocupando a tela toda.
![Screenshot from 2023-08-18 22-22-29](https://github.com/softeam-org/icose-web/assets/88282291/0afb7cc9-a260-4f04-aa89-48d2d7d5342d)

2023-08-19 14:40 UTC, DanielSenaDev commented on src/Pages/Projetos.jsx
Foi realizado o ajuste conforme solicitado #21

2023-08-19 18:02 UTC, biribas requested changes
Vamos abstrair esses três componentes de projetos para um único componente Project.
O componente Project receberá duas proriedades como parâmetro: o título do projeto e sua descrição. Como as descrições dos projetos podem ser variadas (conter fotos, tópicos, etc), crie componentes para cada descrição (na real você já os tem criado, apenas os modifique para atender os requisitos acima).

Além disso, em Projetos.jsx, crie uma lista de componentes Project. Essa abordagem automatizará o processo de adicionar um novo projeto na página.

2023-08-22 06:58 UTC, DanielSenaDev commented
- Os projetos estão componetizados
- Novos projetos devem ser inseridos em "src/components/Projects/Contents/" como um jsx
- O projects.js dentro da pasta data deve também ser alterado adicionando um titulo e o filename

2023-08-22 13:40 UTC, biribas requested changes
Está quase bom, só precisa de um pequeno ajuste. Você salvou o título no arquivo data/projects.js mas o reescreve dentro dos aquivos dos componemntes.  Não o reescreva, importe o título de projects.js. Essa abordagem facilitará possíveis futuras manutenções no código.

Para lidar com isso, recomendo criar um componente Project.jsx, que representa um projeto arbitrário. Ele vai duas propriedades (parâmetros): o título (salvo em data/projects.js) e o componente que você já criou que contém a descrição do projeto (nome do componente também salvo em data/projects.js).

Listei também algumas correções simples em cada código

2023-08-22 13:40 UTC, biribas commented on src/components/Projects/Contents/ConhecendoTerritorio.jsx
Apagar título. Esse componente vai ser responsável apenas por renderizar a descrição do projeto.

2023-08-22 13:40 UTC, biribas commented on src/components/Projects/Contents/MaratonaSolidariedade.jsx
Apagar título. Esse componente vai ser responsável apenas por renderizar a descrição do projeto.

2023-08-22 13:40 UTC, biribas commented on src/components/Projects/Contents/RecantoPassaros.jsx
Apagar título. Esse componente vai ser responsável apenas por renderizar a descrição do projeto.

2023-08-22 13:40 UTC, biribas commented on src/components/Projects/ProjectRender.jsx
Leia o comentário principal ☝️

2023-08-22 13:40 UTC, biribas commented on src/Pages/Projetos.jsx
O footer sobe quando a tela está pequena. Você pode empurrar ele pra baixo usando flex: 1 no section.
![image](https://github.com/softeam-org/icose-web/assets/88282291/8aff8b04-2d82-48fc-907a-acff533efe85)

2023-08-22 15:29 UTC, DanielSenaDev commented on src/components/Projects/ProjectRender.jsx
Estou com duvida sobre esse "...criar um componente Project.jsx, que representa um projeto arbitrário..."
A ProjectRender.jsx está fazendo isso, mas não tem parametros, ele obtem o conteudo com um map.

2023-08-22 15:57 UTC, biribas commented on src/components/Projects/ProjectRender.jsx
Ele está renderizando todos os projetos (no caso atual, 3 projetos). A ideia que eu comentei é você criar um componente que renderiza um único projeto arbitrário. Ele receberia o título e o conteúdo como parâmetro.
O título seria passado como uma string e o conteúdo como um componente (dá pra passar componentes por parâmetro) .

2023-08-23 13:20 UTC, marcelomotadev commented on src/components/Projects/ProjectRender.jsx
Mas o título também está presente no componente, você quer que desfaça, seria isso?

2023-08-24 00:17 UTC, biribas requested changes
Tá perfeito. Só precisa agora de dois ajustes bestinhas. 
1 - Remover a classe informada no comentário abaixo
2 - Mudar padding informado no comentário abaixo

2023-08-24 00:17 UTC, biribas commented on src/components/Header/PageLink.jsx
Remover essa classe

2023-08-24 00:17 UTC, biribas commented on src/Pages/Projetos.jsx
Mudar px-20 para px-12. Estamos usando esse padrão em todas as páginas

2023-08-25 20:17 UTC, DanielSenaDev commented
> Tá perfeito. Só precisa agora de dois ajustes bestinhas. 1 - Remover a classe informada no comentário abaixo 2 - Mudar padding informado no comentário abaixo

Foi feito as alteracoes, esta no PR #39  para a dev aguardando o merge

2023-08-26 13:45 UTC, closed without merging